### ISSUE TITLE
Build a script the "old way" which sweeps parameters of pixel count and outputs a bunch of files

### ISSUE THREAD

**Issue by jeffbaumes** [girder/large_image#1061]
Use VIPS sink to build separate TIFF files.
Use YAML file to combine TIFF files into a 1-D or 2-D stack using a multi-source source. (The input for "multi-source source" is a YAML file)

In the future, this will become much less clunky. The new way will use a backend (xarray or HDF5 or ??) to build all the data at once and save a single TIFF with everything in one step.

**Comment by manthey** [comment]
Done in #1051.
