### ISSUE TITLE
Disable opacity or make opacity in frame selector functional

### ISSUE THREAD

**Issue by jeffbaumes** [girder/large_image#1110]

**Comment by manthey** [comment]
What exactly would this mean?  Currently, we composite bands via either a maximum (for everything but alpha channels) or multiply (for alpha channels) effect.  We currently render via JPG and have the tile layers stacked conceptually in the viewer so panning to an unloaded area will show a lower resolution until the higher resolution is loaded.

If you composite with an alpha channel, then we have to switch to rendering with PNG and only show the current tile layer (this is done when we do things like image overlays).  For a single base image, this would let the background of the webpage show through, which probably isn't what is desired.

But, we could check if any band has a non unity opacity and switch to the single level/PNG rendering in that case.  Until we do that, we should just disable selecting translucent colors.

**Comment by jeffbaumes** [comment]
I do not know exactly what this would mean, but I believe we either disable opacity in the color selector or make it do something. I updated the issue title to reflect this.

**Comment by manthey** [comment]
@annehaley has disabled it in the color selector in https://github.com/girder/large_image/pull/1086.  We can revisit this later when desired.

**Comment by manthey** [comment]
Resolved in #1086.
