### ISSUE TITLE
ipyleaflet coordinate issues for non-geo images

### ISSUE THREAD

**Issue by banesullivan** [girder/large_image#1213]
Follow up to #1065  https://github.com/girder/large_image/pull/1065#pullrequestreview-1488835256

There are some issues with the coordinate system for non-geospatial images in the `ipyleaflet` viewer that need to be resolved. Let's see how people use this viewer and gather a list of issues to address here

FYI, I posted this issue in `ipyleaflet` for help: https://github.com/jupyter-widgets/ipyleaflet/issues/1117

**Comment by manthey** [comment]
Largely resolved by #1249.  We'll open specific issues as they come up.
