### ISSUE TITLE
Add support for downloading files from a DICOMweb server

### ISSUE THREAD

**Issue by psavery** [girder/large_image#1309]
This will require implementing [this function](https://github.com/girder/large_image/blob/9cc82cdff75ddaf8943877d03129a67cf42c5073/sources/dicom/large_image_source_dicom/assetstore/dicomweb_assetstore_adapter.py#L95-L109).

It would be beneficial to support offsetting, if possible.

Note the discussion [here](https://github.com/girder/large_image/pull/1303#discussion_r1329076538).

**Comment by psavery** [comment]
One thing that complicates this is that currently each item is associated with a series, and there is a single file per item. However, each series typically contains more than one DICOM file (which is often referred to as an "instance"). 

We could, for instance, use [this function](https://dicomweb-client.readthedocs.io/en/latest/package.html#dicomweb_client.api.DICOMClient.retrieve_series) to retrieve all instances in a series. However, this is likely to return multiple DICOM datasets (each of which can be written to a file).

Alternatively, [this function](https://dicomweb-client.readthedocs.io/en/latest/package.html#dicomweb_client.api.DICOMClient.retrieve_instance) can be used to retrieve a single instance (a.k.a., a single DICOM dataset).

Perhaps we should modify our assetstore model to make separate files for each instance, so we can more easily support downloading files?

For actually downloading the files themselves (as raw data in chunks): the `DICOMwebClient` API doesn't provide us an easy way to do this. However, I think we can take inspiration from their code. For instance, [this function](https://github.com/ImagingDataCommons/dicomweb-client/blob/39dc8a799fac508756d9df57cf16fea51d54a9c3/src/dicomweb_client/web.py#L1026-L1033) is a way to obtain a resource in chunks. We could obtain a DICOM file this way (using the `application/dicom` content type), as long as we can figure out the URL as well.

**Comment by manthey** [comment]
If we used the `retrieve_series` to get all of the files conceptually, and downloaded them and then created a zip of those, does that zip file open with our dicom source reader?  If so, perhaps we should expose that conceptually (range requests will be tricky, but if the individual files don't have further compression inside the zip, this could work).
