### ISSUE TITLE
removing gdal as a dependency for large-image-converter

### ISSUE THREAD

**Issue by cardinalgeo** [girder/large_image#1462]
Hey folks! I've noticed that gdal is a dependency of `large-image-converter`. Does this need to be the case? gdal can be frustrating to install, especially for novice python users. As some tile sources don't need gdal (e.g., the tiff tile source), it would seem better to just have gdal be a dependency of certain tile sources rather than also `large-image-converter`. 

For example, the scenario in which `large-image-converter` is used alongside a tiff tile source wouldn't *need* gdal but currently requires it as a dependency. Conversely, if a user were using `large-image-converter` with a tile source that did need gdal, gdal would already be a dependency for that tile source and so wouldn't need to be a dependency of `large-image-converter`. Thoughts? 

Best, Robert

**Comment by manthey** [comment]
On linux, we have wheels to make it easy to install GDAL, but we should definitely make it an extras_require.

**Comment by cardinalgeo** [comment]
So happy to see this change — thanks @manthey!
