### ISSUE TITLE
This great library considers using redis as a cache backend?

### ISSUE THREAD

**Issue by nipeone** [girder/large_image#1468]
Is it possible to add redis as an option？some scenarios already use redis, so use redis directly as a cache backend for large-image

**Comment by manthey** [comment]
Currently we cache tiles either in the main process memory or in memcached.  It _should_ be easy to add additional cache backends.  Caches can be implements as plugins which expose the `large_image.cache` in their `entry_points` and have that as a `cachetools.Cache` style cache that implements appropriate get and set methods, plus an extra `getCache` staticmethod which returns a instance of the cache class and an optional lock, if needed.

**Comment by manthey** [comment]
If you like; or it could be a stand-alone package with just the redis cache.
