### ISSUE TITLE
limit bounds in openslide source

### ISSUE THREAD

**Issue by nipeone** [girder/large_image#1470]
In the sources of openslide, is it considered to make full use of the four properties 

- openslide.bounds-x
- openslide.bounds-y
- openslide.bounds-width
- openslide.bounds-height 

to render the non-empty slide region?

some slides have a large sizeX and sizeY, e.g. (78786, 180026)，but the actual non-empty area is very small，e.g. (62526, 61395), such as the following mirax's slide.
![image](https://github.com/girder/large_image/assets/4449628/1b633778-eb8f-4f32-89d3-93757b8568e1)

**Comment by manthey** [comment]
It looks like this only ever set for Mirax and Leica SCN.  We'd want to adjust the sizeX and sizeY parameters to the width and height in the tile source and add the appropriate x and y offsets. 

The drawback is that any existing sources that end up getting cropped will look different in Girder and annotations may not be lined up in the expected manner.

**Comment by nipeone** [comment]
Maybe you're right to consider the drawback, but wouldn't it make more sense to allow an option like this？

**Comment by nipeone** [comment]
> It looks like this only ever set for Mirax and Leica SCN. We'd want to adjust the sizeX and sizeY parameters to the width and height in the tile source and add the appropriate x and y offsets.
> 
> The drawback is that any existing sources that end up getting cropped will look different in Girder and annotations may not be lined up in the expected manner.↳
> 
@manthey hi, how to add x and y offsets, is there any examples in doc？

**Comment by nipeone** [comment]
is there any method to change tile backgroud color in tile serving?When I open it with histomicsUI, it presents a black background，but it's white background when i open it using qupath or openslide.DeepzoomGenerator

![image](https://github.com/girder/large_image/assets/4449628/24d05e55-c6b6-4902-a6dc-de2da269a880)

**Comment by nipeone** [comment]
> is there any method to change tile backgroud color in tile serving?When I open it with histomicsUI, it presents a black background，but it's white background when i open it using qupath or openslide.DeepzoomGenerator↳
> 
> ![image](https://private-user-images.githubusercontent.com/4449628/335097299-24d05e55-c6b6-4902-a6dc-de2da269a880.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzk1NDQsIm5iZiI6MTcxNzEzOTI0NCwicGF0aCI6Ii80NDQ5NjI4LzMzNTA5NzI5OS0yNGQwNWU1NS1jNmI2LTQ5MDItYTZkYy1kZTJkYTI2OWE4ODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzFUMDcwNzI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDU4ZDBmMGIyYjZhOTNkYjUxNWRjNmU3Y2ExYThlYjdhNzA0ZjVhNTE0YzJlNjlhNGJlOWQzYzA4OWM4NzIwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VM4K_wFgKK9PQIESjjZfMJhAfLcMl3LSDaadh6Iasro)

@manthey i found some code in openslide.deepzoom to change tile background.
```
  tile = self._osr.read_region(*args)
  profile = tile.info.get('icc_profile')

  # Apply on solid background
  bg = Image.new('RGB', tile.size, self._bg_color)
  tile = Image.composite(tile, bg, tile)
```
Is there a corresponding operation or document in large_image?

**Comment by manthey** [comment]
> > is there any method to change tile backgroud color in tile serving?When I open it with histomicsUI, it presents a black background，but it's white background when i open it using qupath or openslide.DeepzoomGenerator↳
> > ![image](https://private-user-images.githubusercontent.com/4449628/335097299-24d05e55-c6b6-4902-a6dc-de2da269a880.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzk1NDQsIm5iZiI6MTcxNzEzOTI0NCwicGF0aCI6Ii80NDQ5NjI4LzMzNTA5NzI5OS0yNGQwNWU1NS1jNmI2LTQ5MDItYTZkYy1kZTJkYTI2OWE4ODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzFUMDcwNzI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDU4ZDBmMGIyYjZhOTNkYjUxNWRjNmU3Y2ExYThlYjdhNzA0ZjVhNTE0YzJlNjlhNGJlOWQzYzA4OWM4NzIwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VM4K_wFgKK9PQIESjjZfMJhAfLcMl3LSDaadh6Iasro)
> 
> @manthey i found some code in openslide.deepzoom to change tile background.
> 
> ```
>   tile = self._osr.read_region(*args)
>   profile = tile.info.get('icc_profile')
> 
>   # Apply on solid background
>   bg = Image.new('RGB', tile.size, self._bg_color)
>   tile = Image.composite(tile, bg, tile)
> ```
> 
> Is there a corresponding operation or document in large_image?

Is this what you are looking for: 
https://girder.github.io/large_image/tilesource_options.html#edges
Or, in the rest  call to the tiles/zxy endpoint add `?edge=<color>`.  If you need more control, the style parameter can be used to modify the image tiles themselves.

**Comment by nipeone** [comment]
> > > is there any method to change tile backgroud color in tile serving?When I open it with histomicsUI, it presents a black background，but it's white background when i open it using qupath or openslide.DeepzoomGenerator↳
> > > ![image](https://private-user-images.githubusercontent.com/4449628/335097299-24d05e55-c6b6-4902-a6dc-de2da269a880.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzk1NDQsIm5iZiI6MTcxNzEzOTI0NCwicGF0aCI6Ii80NDQ5NjI4LzMzNTA5NzI5OS0yNGQwNWU1NS1jNmI2LTQ5MDItYTZkYy1kZTJkYTI2OWE4ODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzFUMDcwNzI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDU4ZDBmMGIyYjZhOTNkYjUxNWRjNmU3Y2ExYThlYjdhNzA0ZjVhNTE0YzJlNjlhNGJlOWQzYzA4OWM4NzIwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VM4K_wFgKK9PQIESjjZfMJhAfLcMl3LSDaadh6Iasro)
> > 
> > 
> > @manthey i found some code in openslide.deepzoom to change tile background.
> > ```
> >   tile = self._osr.read_region(*args)
> >   profile = tile.info.get('icc_profile')
> > 
> >   # Apply on solid background
> >   bg = Image.new('RGB', tile.size, self._bg_color)
> >   tile = Image.composite(tile, bg, tile)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is there a corresponding operation or document in large_image?
> 
> Is this what you are looking for: https://girder.github.io/large_image/tilesource_options.html#edges Or, in the rest call to the tiles/zxy endpoint add `?edge=<color>`. If you need more control, the style parameter can be used to modify the image tiles themselves.↳

thanks, finally i solve the problem use this style.
```
style = {'bands': [
        {"band": 1, "palette": ["#000", "#f00"]},
        {"band": 2, "palette": ["#000", "#0f0"]}, 
        {"band": 3, "palette": ["#000", "#00f"]},
        {"band": 4, "palette": ["#fff", "#000"]}
    ]}
```
