### ISSUE TITLE
Make rotation optional and change default of fillColor in rectangle annotations

### ISSUE THREAD

**Issue by cdeepakroy** [girder/large_image#158]
Currently, for [rectangle annotations](https://github.com/girder/large_image/blob/master/docs/annotations.md#rectangle) the rotation is a required attribute. This issue proposes to make this an optional parameter with default value of zero. 

Also set the default value of fillColor to "rgba(0, 0, 0, 0)" which represents no fill.

**Comment by cdeepakroy** [comment]
CC: @manthey, @jbeezley

**Comment by manthey** [comment]
These are two separate things -- the rotation requirement can be changed the annotation schema.  The default fill color should be adjusted in our instantiation of geojs (and if a fill color is specified, it would override it, of course).
