### ISSUE TITLE
Query annotations by area and zoom level

### ISSUE THREAD

**Issue by manthey** [girder/large_image#170]
The GET annotation/{id} should either be extended or a new endpoint be created that will return annotations that are within a specified rectangle and some minimum size for a particular zoom level.

This will require a spatial index.  We will probably want to precompute extents of annotations.  Annotations smaller than some size (1 pixel, for instance) at a zoom level should be able to be excluded -- I think the 'minor radius' of the annotation is the relevant metric for this.  We will want any annotation that overlaps the specified region, and it will be better to err on giving some annotations that are not strictly necessary than on being too exclusive (for instance, a polyline that surrounds the region but doesn't enter it can be returned).

**Comment by manthey** [comment]
A limit for the total number of annotations returned would be useful, too. 

Querying by a list of types of annotations may also be desirable.

**Comment by manthey** [comment]
Simplistically, each annotation has a bounding box and a minimum size.  The minimum size can crudely be the minimum of the width and height of the bounding box.  It would be used as the threshold of whether to show the annotation at a particular zoom level.

Points, however, have zero-area bounding box, , so we may wish to artificially include them at some other resolution.  If we have a line (not a polygon), then pedantically, it has the same problem as a point, in that it has no breadth.  If we are using the bounding box for the size threshold, then this is only a problem if it is vertical or horizontal.  

I can see it to be useful to also include:
- limiting the number of annotations returned by either a fixed number or by a number relative to their complexity (so fewer complex polygons would be returned than points).  A complexity based threshold would ensure that the viewer always has enough resources to show what we send it, even if it has to only show some of the annotations because of it
- filling the limit request with elements outside of the strict bounding box so that (slow) panning doesn't have perceptible lag in showing annotations.  This could just be accomplished by asking for a larger region in the client (which would be easier).

I think we'll need to precompute the bounding boxes as we save the annotation elements, as it will otherwise be prohibitively slow to make our queries.

**Comment by zachmullen** [comment]
I think minimum zoom level at which an annotation appears should be an out-of-band piece of metadata -- I could see it being useful to show very small annotations even at low magnification (perhaps rendered as something other than a rectangle), just so a user knows on which section they should zoom in.

**Comment by manthey** [comment]
I was thinking that if each feature had a size-like parameter, then it can be used as an optional query, so that a client can choose what threshold should be used for that.

If we have a limit to the query, then the sort order becomes important on what gets returned when the limit is reached.  We can expose a sort parameter.  Or we can pick something to start with and expand to a sort parameter later.  I see using distance from center of view and size as useful sorts.

**Comment by manthey** [comment]
Resolved by PR #180.
