### ISSUE TITLE
Add utility function for converting point coordinates between magnifications

### ISSUE THREAD

**Issue by manthey** [girder/large_image#223]

**Comment by manthey** [comment]
@slee172, @cdeepakroy What would the preferred API for this look like?  For instance,
```
point = (x, y)
scaledPoint = tilesource.getPointAtAnotherScale(point, sourceScale, sourceUnits, targetScale, targetUnits)
```
where `sourceScale`, `targetScale`, and `targetUnits` are identical to the parameters that can get passed to `convertRegionScale`.

As an example, if you have coordinates at magnification 5 and want them in the base units coordinates, this would be
```
scaledPoint = tilesource.getPointAtAnotherScale(point, sourceScale={'magnification': 5}, sourceUnits='mag_pixels', targetUnits='base_pixels')
```

**Comment by slee172** [comment]
This looks good to me.

**Comment by manthey** [comment]
Added in PR #230.
