### ISSUE TITLE
POST /tiles endpoint hangs indefinitely on non-image file

### ISSUE THREAD

**Issue by danlamanna** [girder/large_image#224]
When calling /tiles on an item which isn't an image (a json file in this instance) the request hangs indefinitely, it appears to happen in the call to `PIL.Image.open`.

**Comment by manthey** [comment]
What does PIL.Image.open do with the file from a python REPL?

**Comment by danlamanna** [comment]
```
IOError: cannot identify image file 'annotation.json'
```

(Though it does take a few seconds to appear)

**Comment by manthey** [comment]
When I try this on an arbitrary json file I have, I get a failure message.  Can you share the specific file you are using?

**Comment by manthey** [comment]
When I try the same file in my instance of large image, the POST endpoint returns a job, and the job properly fails some time later.  I did via curl, but I assume the grider client's post method would be the same.

**Comment by manthey** [comment]
I was unable to reproduce this, even with @danlamanna's sample file.  We can revisit it if we find another case that can cause the issue.
