### ISSUE TITLE
Magnification issue on getSingleTile in large_image

### ISSUE THREAD

**Issue by slee172** [girder/large_image#226]
Magnification is not properly changed when using it on 40x. For example, when using 40x slide with input arguments(magnification = 5 and tile_size = 2048) on getSingTile, it returns 10x as a magnification.

**Comment by slee172** [comment]
Here're some code snippet.

```
print('\n>> Reading input image ... \n')
ts = large_image.getTileSource(img_paths[i])
ts_metadata = ts.getMetadata()
print json.dumps(ts_metadata, indent=2)
```
>> Reading input image ... 

{
  "magnification": 40.0, 
  "levels": 11, 
  "tileHeight": 240, 
  "tileWidth": 240, 
  "sizeX": 129472, 
  "sizeY": 90209, 
  "mm_y": 0.00024650000000000003, 
  "mm_x": 0.00024650000000000003
}

**Comment by cooperlab** [comment]
@manthey My guess is that this is not related to 40X, but is a general issue with requesting data from a layer that doesn't exist in the pyramid. The 40X images may not have a 5X layer, and so when we request a 2048x2048 region at 5X, we get a 4096x4096 region at 10X instead.

**Comment by manthey** [comment]
Yes, the sample file has a 10X level but not a 5X level.  However, there is still a bug.

`tileIterator` and its variants (which include `getSingleTile`) has an optional parameter `resample` to determine if only pixels from the original file are returned or resampling is allowed.  This defaults to `False`, which then gives the next higher existing level (which is what is happening here).  However, when `resample=True`, this doesn't actually do what we want -- it takes the 2048x2048 tile at magnification 10X and then scales that (ending with a 1024x1024 tile).  Plus there are some float/integer issues when inexact magnifications are used.

I'll have a fix soon.

**Comment by manthey** [comment]
PR #227 fixes this.
