### ISSUE TITLE
Add support for reading DeepZoom files

### ISSUE THREAD

**Issue by brianhelba** [girder/large_image#31]
http://libvips.blogspot.co.uk/2013/03/making-deepzoom-zoomify-and-google-maps.html

**Comment by manthey** [comment]
DeepZoom files consist of a file names `<name>.dzi` or `<name>.xml`, plus a directory called `<name>_files` with directories named by resolution level `0`, `1`, `2`, ..., where `0` is the 1 pixel x 1 pixel image.  Within directories, files are named `<x>_<y>.<format>`.  The final tiles are partial.

Note that tiles can have overlap, so for the general tile source, returning a trimmed tile might be the way to go.
