### ISSUE TITLE
Improve management of docker image used for CI

### ISSUE THREAD

**Issue by jcfr** [girder/large_image#414]
The image described in https://github.com/girder/large_image/blob/master/Dockerfile is currently published as `zachmullen/tox-and-node` and used in https://github.com/girder/large_image/blob/ee805aa90c86fb197fecda9df3848bd2c6d32b7d/.circleci/config.yml#L6

I suggest to document how to rebuild the image and how to publish it on dockerhub.

Ideally, the image should be published in a project specific dockerhub organization.

Last, if this type of image is useful for other web effort, I wonder if should start agrageting them in common repository (a like what we do with [dockcross](https://github.com/dockcross/dockcross)) but that may be a stretch

Cc: @subdavis @mgrauer @zachmullen

**Comment by manthey** [comment]
Resolved with #429.
