### ISSUE TITLE
Trouble with getTileSource for RGB UInt8 TIFF file

### ISSUE THREAD

**Issue by asasama12** [girder/large_image#445]
I have an image that was converted from a .scn file to a RGB uint8 numpy array and then resaved as a tiff file.  With large_image, getTileSource works on the .scn file but not for the Tiff file.  I get an exception.    

![image](https://user-images.githubusercontent.com/41748563/81586426-19b87180-937b-11ea-926b-90ad69b0bc3e.png)

It would very helpful to me if I could use the Tiff files for my analysis since they have been registered while the .scn files have not.  Am I missing something in how to load in these tiff files, or is there some way to convert them into a format that large_image can deal with better? 

thanks,

**Comment by manthey** [comment]
Superficially, it sounds like the tiff file you created is not stored as a multi-resolution file.  If you are using Girder, clicking on the large-image button on an item will automatically create a multi-resolution tiff file that will work with large image.  You can also do this directly on the command line with vips (there are other tools besides vips that work, too).

**Comment by asasama12** [comment]
I think that is exactly the reason! thanks!
I am not using Girder, I have been using large_image and histomikstk through jupyter.  Is there some documentation or guide for how to do this with vips or other package?

**Comment by manthey** [comment]
As a basic command using vips:
```
vips tiffsave inputfile.dat outputfile.tiff --compression jpeg -Q 95 --tile --tile-width 256 --tile-height 256 --pyramid --bigtiff
```
where `inputfile.dat` is the path of your source file and `outputtile.tiff` is the place to store the output.

vips has lots of options.  See https://libvips.github.io/libvips/API/current/VipsForeignSave.html#vips-tiffsave.

**Comment by asasama12** [comment]
This is working great for me!  Thanks!
