### ISSUE TITLE
Opening pyramidal images ob google collab: large_image getTileSource doesn't work on google collab (No available tilesource for ndpi)

### ISSUE THREAD

**Issue by asmagen** [girder/large_image#452]
I used all of these commands to make sure I have everything that's needed for loading dpi pyramidal images on google collab with no luck so far.

    !pip install large_image
    !apt update && apt install -y openslide-tools
    !pip install openslide-python
    !pip install libtiff openslide_python pyvips gdal mapnik pyproj glymur -f https://girder.github.io/large_image_wheels
!pip install large-image-source-openslide

I get the following error:

    ---------------------------------------------------------------------------
    TileSourceException                       Traceback (most recent call last)
    <ipython-input-23-0584be72095d> in <module>()
         27 print(os.listdir(ndpi_dir))
         28 print(target_filename)
    ---> 29 ts = large_image.getTileSource(target_filename)
         30 
         31 # print(ts.getMetadata())
    
    1 frames
    /usr/local/lib/python3.6/dist-packages/large_image/tilesource/__init__.py in getTileSourceFromDict(availableSources, pathOrUri, *args, **kwargs)
         65         if availableSources[sourceName].canRead(sourceObj, *args, **kwargs):
         66             return availableSources[sourceName](sourceObj, *args, **kwargs)
    ---> 67     raise TileSourceException('No available tilesource for %s' % pathOrUri)
         68 
         69 
    
    TileSourceException: No available c for ndpi_images/Li88TDCLAMP.ndpi

I made sure the the file is there, it's loading okay in other platforms using the same command, so it's not the file. 

How can I resolve this issue?

Thanks

**Comment by asmagen** [comment]
I'm actually surprised that after repeating this rather desperate exercise of reinstalling everything and restarting the kernels somehow resolved the issue and the slides are loading. I'm still curious how are these things possible? I had all of the requirements installed, I loaded the libraries, and got this very frustrating error.

**Comment by manthey** [comment]
large_image has different tile sources; if they aren't installed they won't read specific formats.  I would expect the following to work and install all sources (without any need for using `apt`):
```
pip install large_image[sources] -f https://girder.github.io/large_image_wheels
```

**Comment by asmagen** [comment]
Thanks @manthey 

The odd issue that I’d like to resolve is that I can load images only after installing and then restarting the session (the compute instance, Google Colab or Saturn Cloud etc). If I don’t restart the session after the installation, it gives the error discussed above. I can keep doing that but I thought it’s inefficient and there must be an explanation and solution. Any thoughts?

**Comment by manthey** [comment]
This turns out to be an issue with pkg_resources caching information about available packages.  As of python 3.8, the recommended change is to switch from using pkg_resources to importlib.metadata to enumerate entry_points (used to find plugins, such as the tile sources).  For older pythons, there is a backported package.  There will shortly be a PR to do this.

If you are using an older version, you can force Google colab to reload the appropriate information by adding
```
import pkg_resources
pkg_resources._initialize_master_working_set()
```
after the `!pip install` and before trying to load a tile source.
