### ISSUE TITLE
Can't seem to install mapnik correctly

### ISSUE THREAD

**Issue by markbuckup** [girder/large_image#468]
Mapnik is the only tile giving me issues when downloading. It says I already have it but still throws the error that the requirement isn't met. I'm trying to fully download large_image so that I can then work with HistomicsTK. Any tips?

<img width="1026" alt="Screen Shot 2020-07-20 at 18 41 43" src="https://user-images.githubusercontent.com/56090031/87993579-e0a62700-cab8-11ea-8eda-40d478954acf.png">

**Comment by manthey** [comment]
If you are on linux, you can install it from our published wheels (e.g., `pip install large-image-source-mapnik --find-links https://girder.github.io/large_image_wheels`).

If you are on OSX or some other non-linux system, it is probably easiest to change HistomicsTK's setup.py file to not require tile sources explicitly (change the dependency from `large_image[sources]` to `large_image` and only install the tile sources you actually use -- most tile sources need binary libraries.

**Comment by markbuckup** [comment]
Thank you. This advice worked.
