### ISSUE TITLE
Django support

### ISSUE THREAD

**Issue by manthey** [girder/large_image#524]
For projects using Django rather than Girder, having a Django app that adds a tile server and other large_image support is desired.

This can be added in parts.  At the core, we need to decide how to add a model mixin or field extension so that a file field can be used as a large image.  As part of this, we may need to convert an existing file to a file that can be used directly, so this needs some way to store a converted file and associate it with the original (deleting it when the original is deleted).

The functionality of the Girder plugin can be reproduced in stages rather than all at once.  A potential order for doing this would be:

- [ ] endpoint or method to make / unmake a Django file field into a large_image item
- [ ] endpoints for metadata (/tiles, /tiles/internal_metadata)
- [ ] endpoints for serving tiles (/tiles/zxy, /tiles/fzxy)
- [ ] cache management - tile sources should be cached so that we don't open a file for each tile
- [ ] fuse-like ability to access filefields as os-level files (until implemented, s3 files will need to be pulled locally to serve them, which is inefficient)
- [ ] endpoint for regions
- [ ] endpoint for thumbnails
- [ ] endpoints for associated images
- [ ] thumbnail caching (of both WSI and associated images)
- [ ] endpoint for individual pixels
- [ ] endpoint for histograms
- [ ] some diagnostic and settings endpoints (list available sources, set whether to automatically use large_images and the size of small images that can be used)
- [ ] ability to precache thumbnails (the thumbnail jobs endpoints)
- [ ] ability to convert images via large_image_converter
- [ ] endpoints for serving tiles in deepzoom format

To complete the girder plugin functionality, we also need to consider UI extensions for item views and item lists.

This does not include the Girder large image annotation plugin features.

**Comment by banesullivan** [comment]
Much of this is available in RGD at this point. Should we revisit this and see what is still missing and/or make sure this functionality is reusable?

**Comment by banesullivan** [comment]
I've begun creating a new `django-large-image` App in https://github.com/ResonantGeoData/django-large-image

This is currently experimental, but I plan to implement most of the items on the checklist here.

The app abstracts file management so that downstream projects/apps must implement their own file management which greatly simplifies the scope of the new package

**Comment by manthey** [comment]
Awesome.  Once you think that is far enough along, we should close this issue and handle everything in that repo.  Would it be clearer if we transferred that repo from the ResonantGeoData to girder GitHub organizations?

**Comment by banesullivan** [comment]
[`django-large-image`](https://github.com/ResonantGeoData/django-large-image) is in a working state! I think it's time we close this issue and follow up with new issues in that repository.

**Comment by banesullivan** [comment]
> Would it be clearer if we transferred that repo from the ResonantGeoData to girder GitHub organizations?

I think we should. Will follow up internally

**Comment by manthey** [comment]
Awesome.
