### ISSUE TITLE
Support getBandInformation in PILFileTileSource

### ISSUE THREAD

**Issue by banesullivan** [girder/large_image#618]
It would be great if `PILFileTileSource` could implement the same `getBandInformation` as `GDALFileTileSource`. For example, I want to extract general band info from a JPEG image. `rasterio` lets me do this (though it throws warnings), but `large_image` does not. Well really, I just want to know the "interpretation" of each band (not any stats) and that's all that rasterio will return.

Could `PILFileTileSource` implement `getBandInformation` in a way that simply returns the interpretations? e.g. "red", "blue", "green", "grey", etc.

**Comment by banesullivan** [comment]
Also, I need a way to get the number of banda in the image

**Comment by manthey** [comment]
It isn't as uniform, but this information is available via the `getInternalMetadata` method.  I think expanding `getBandInformation` to all tile sources is a good idea.

**Comment by banesullivan** [comment]
> It isn't as uniform, but this information is available via the getInternalMetadata method

Are you referring to the `mode` field? e.g.

```py
In [10]: pil_source.getInternalMetadata()
Out[10]:
{'pil': {'filename': '/Users/bane/Desktop/000000245915.jpg',
  'format': 'JPEG',
  'mode': 'RGB',
  'size': (500, 333),
  'width': 500,
  'height': 333,
  'palette': None,
  'info': {'jfif': 257,
   'jfif_version': (1, 1),
   'dpi': (72, 72),
   'jfif_unit': 1,
   'jfif_density': (72, 72)}}}

In [11]:
```

Looking at https://pillow.readthedocs.io/en/stable/handbook/concepts.html#modes, I'm not sure how I could consistently use that to get the number of bands without creating a mapping manually

**Comment by manthey** [comment]
Indeed.  You'd have to know that `mode` maps to the bands in the PIL.  `getInternalMetadata` is the catch-all for known metadata.  As another function that is the wrong choice, the `histogram` function returns a histogram per band (so the length of its output would tell you the number of bands).

I'll get to this soon.

**Comment by manthey** [comment]
See https://github.com/girder/large_image/pull/622
