### ISSUE TITLE
Support image overlay annotations

### ISSUE THREAD

**Issue by manthey** [girder/large_image#678]
Add image overlay annotations to the schema and renderer of the girder_annotation module.

Specifically, an image annotation needs to contain:
- an image (this could be a relative path to the main image, or a Girder image ID).  Images should themselves be large_image or directly readable via a common browser (e.g., png or jpeg)
- default opacity for the image (if unset, this defaults to 1)
- default location for the image
  I'm not sure the best format for this, as we could be very general (e.g., (a) upper-left, width, and height, (b) center, rotation, scale, (c) all four corners, (d) affine transform matrix, etc.)
  By default, this would place the image at the upper left in its native resolution

Check what others have done for this (I think that there is a Girder 1 implementation of this on GitHub).

Relative paths are probably conceptually in the Girder resource path space (since that will translate to physical filesystems directly and is clear what it means in remote assetstores).

**Comment by manthey** [comment]
Since primary files are often copied, we need to make sure that they remain associated with the copied primary file.  This can be done as a separate task from the basic implementation.

**Comment by naglepuff** [comment]
> Check what others have done for this (I think that there is a Girder 1 implementation of this on GitHub).

Do you know where I might be able to find this attempt? Would it be here in the `large_image` repo or an older branch of the `girder` repo?

**Comment by manthey** [comment]
I'm guessing it is here: https://github.com/abcsFrederick/overlays, but it may be in a different repo within that organization.
