### ISSUE TITLE
caching getRegion results

### ISSUE THREAD

**Issue by banesullivan** [girder/large_image#681]
Would it be possible to cache the results of `getRegion`?

### Example use case

I have a GDAL_WMS (XML file) that specifies a tile server for a large, global DEM. I use `getRegion` to create localized DEMs. I often need to get the same region and it would be great if `large_image` could cache that so that GDAL is not downloading the tiles for that region on each `gdal.Warp` call in `getRegion` This could be implemented by caching the result of `getRegion` with the tile source and the `getRegion` params as the cache key.

------

### Another approach?

I often need to fetch overlapping regions in the above use case as well. Considering a basic caching of `getRegion`'s results would not be able to handle overlapping requests, I'm wondering if it'd be possible to create an "inverse tile server" with large_image that would cache the tiles being pulled by the GDAL_WMS XML file? Or perhaps GDAL has a means of caching the tiles in the WMS file?

**Comment by banesullivan** [comment]
After reading through the docs for the WMS driver in GDAL https://gdal.org/drivers/raster/wms.html, I found that GDAL can be configured to cache the tiles by adding the following to the WMS XML:

```xml
<GDAL_WMS>
  ...
  <Cache>
    <Path>./gdalwmscache</Path>
  </Cache>
</GDAL_WMS>
```

or setting `GDAL_ENABLE_WMS_CACHE=YES` in the environment.

**Comment by banesullivan** [comment]
After doing this, I executed `getRegion` twice on the tile source and saw that the first took a while while the tiles were all downloaded (**Wall time: 2min 56s**) and the second execution finished rapidly as everything was already downloaded (** Wall time: 4.19 s**).

**Comment by banesullivan** [comment]
Using the WMS cache solves my issue, so this can be closed.

@manthey, outside of this use case, do you think it'd be useful to cache `getRegion`?

**Comment by manthey** [comment]
Usually getRegion ends up using cached tiles, so it should be much faster the second time.  I don't think getRegion should cache directly, but it'd be worth running down why the wms tiles weren't cached enough in the tile cache to be sufficient without enabling the gdalwmscache.

**Comment by banesullivan** [comment]
> Usually getRegion ends up using cached tiles, so it should be much faster the second time. I don't think getRegion should cache directly

Agreed - this original intent of this issue is no longer valid.

> but it'd be worth running down why the wms tiles weren't cached enough in the tile cache to be sufficient without enabling the gdalwmscache.

It appears that GDAL will not cache these WMS tiles unless the `<Cache/>` section is present in the file -- global GDAL settings do not seem to allow you to set a default behavior for this. I suspect then that since I'm dealing with such a large dataset that large_image's cache purged much of the data before my second `getRegion` run and thus had to redownload the data.
