### ISSUE TITLE
Band math when for getTile and getRegion

### ISSUE THREAD

**Issue by banesullivan** [girder/large_image#688]
Would it be possible to provide some sort of callable that will perform a mathematical operation on a single band when tile serving?

Let's say I have some massive Digital Elevation Model (DEM) and I want to dynamically produce Hillshade maps from it. Ideally, I'd like to have the tile server do this automatically when serving the tiles.

I imagine this being some sort of option for both `getRegion` and `getTile` so that I can serve tiles with the math applied or get a small ROI with the math applied.

Example math:

<details>

```py
import numpy as np

# https://github.com/earthlab/earthpy/blob/9ad455e85002a2b026c78685329f8c5b360fde5a/earthpy/spatial.py#L564
def hillshade(arr, azimuth=30, altitude=30):
    """Create hillshade from a numpy array containing elevation data.
    Parameters
    ----------
    arr : numpy array of shape (rows, columns)
        Numpy array with elevation values to be used to created hillshade.
    azimuth : float (default=30)
        The desired azimuth for the hillshade.
    altitude : float (default=30)
        The desired sun angle altitude for the hillshade.
    Returns
    -------
    numpy array
        A numpy array containing hillshade values.
    """
    try:
        x, y = np.gradient(arr)
    except ValueError:
        raise ValueError("Input array should be two-dimensional")

    if azimuth <= 360.0:
        azimuth = 360.0 - azimuth
        azimuthrad = azimuth * np.pi / 180.0
    else:
        raise ValueError(
            "Azimuth value should be less than or equal to 360 degrees"
        )

    if altitude <= 90.0:
        altituderad = altitude * np.pi / 180.0
    else:
        raise ValueError(
            "Altitude value should be less than or equal to 90 degrees"
        )

    slope = np.pi / 2.0 - np.arctan(np.sqrt(x * x + y * y))
    aspect = np.arctan2(-x, y)

    shaded = np.sin(altituderad) * np.sin(slope) + np.cos(
        altituderad
    ) * np.cos(slope) * np.cos((azimuthrad - np.pi / 2.0) - aspect)

    return 255 * (shaded + 1) / 2

```

</details>

NOTE: This is for a personal project

**Comment by banesullivan** [comment]
I could see this being doable for `getTile` but not necessarily for `getRegion` as that is really just a wrapped call to `gdal.Warp` under the hood. With that in mind, I'm wondering if `large_image` can provide any assistance in performing band math on large images?

**Comment by manthey** [comment]
Currently, if you add a sufficiently complicated style, we don't just use gdal.Warp -- instead we apply the style and then generate output from that.  This is less efficient, but allows the same style to be used for tiles and regions.

I like this as a concept -- you could apply any available python function that takes a numpy array and emits a numpy array of equal dimensions, and the style would have something like `functions=["module1.function1", "module2.submodule2.function2"]`.  Maybe it would be better for the function to optionally take multiple parameters (<numpy array>, <tile record>) -- I'm not sure if anything else would be useful; it would still just return a numpy array.

**Comment by manthey** [comment]
@banesullivan This ends up being useful for other purposes, too.  We can do the band math on a per-tile basis (which means regions will end up being affected as they are just made of tiles).  There are some limitations: if the math needs a larger area than the tile itself, the function will end up being more complex.  See PR #960.
