### ISSUE TITLE
Add package to conda-forge

### ISSUE THREAD

**Issue by banesullivan** [girder/large_image#691]
@manthey, I'd be happy to take this on. I will start with `large-image` and `large-image-source-gdal`. We can handle the other source modules when its clear we have it done right

Needed for https://github.com/banesullivan/localtileserver/issues/6 and I think it'll help large_image gain adoption since conda makes installing GDAL a breeze

**Comment by manthey** [comment]
Sure.  Provided we can update the version as part of the CI when we make a new version tag, I'm all for it.

**Comment by banesullivan** [comment]
Correct me if I'm wrong, but since large_image is pure Python itself, we can set up conda-forge to watch PyPI for new versions and it will automatically update itself. The tricky part is getting all of large-image's dependencies right in the conda forge recipe. But hopefully we only have to do that once at the start.

**Comment by manthey** [comment]
Yes, large_image by itself is pure python.

**Comment by banesullivan** [comment]
Work in progress here: conda-forge/staged-recipes#17167

**Comment by banesullivan** [comment]
This is mostly resolved for the geospatial sources. Note that I did not add the mapnik source, because mapnik is not on conda-forge.

I will add a PR later to close this issue that details conda installation instructions in the README

If there is interest later, we can re-open this issue to add all source modules to conda-forge
