### ISSUE TITLE
Make dev install Girder-optional

### ISSUE THREAD

**Issue by banesullivan** [girder/large_image#699]
Can we adjust the dev install to let Girder be optional and only have those tests run if Gider is installed?

Ran into this issue locally:

![Screen Shot 2021-11-30 at 10 50 47 AM](https://user-images.githubusercontent.com/22067021/144101008-13499950-6222-4cc2-b5ab-6b1237248928.png)

**Comment by manthey** [comment]
Would you expect there to be two `requirements-*.txt` files?  If so, since `requirements-dev.txt` currently installs the requirements for all of the subpackages, maybe a girder-less version would be called `requirements-dev-lib.txt`?  Other naming suggestions welcome.

**Comment by banesullivan** [comment]
> Would you expect there to be two requirements-*.txt files?

I think this makes sens in many cases, yes - for example in PyVista, we have 4 https://github.com/pyvista/pyvista. One for testing, one for lining, one for building the docs, etc

> maybe a girder-less version would be called requirements-dev-lib.txt?

Perhaps `requirements-dev-core.txt`?
