### ISSUE TITLE
Ship LICENSE and README with source modules

### ISSUE THREAD

**Issue by banesullivan** [girder/large_image#703]
Currently only `large-image` ships the sdist with the LICENSE file

Conda-forge requires all modules to ship with a license. Builds are failing here: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=422860&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=1996

blocks #691

**Comment by manthey** [comment]
Added in #704.
