### ISSUE TITLE
Allow `dict` for `style`

### ISSUE THREAD

**Issue by banesullivan** [girder/large_image#730]
Currently, I think only JSON strings work when passing a `style` to `large_image.open()` -- could we support `dict`s as well? I'm not sure how this is being used under the hood, but perhaps this would be as simple as adding:

```py
if isinstance(style, dict):
    style = json.dumps(style)
```

**Comment by manthey** [comment]
The json is simply loaded (e.g., ```
                self.style = json.loads(style)
                if not isinstance(self.style, dict):
                    raise TypeError
```, and is otherwise used as part of the hash to determine if we already have the tile source open.  I think the only impact is how a dictionary would be serialized for that hash; but that should be consistent in all versions of Python we support.
