### ISSUE TITLE
GDAL source support https:// and s3://

### ISSUE THREAD

**Issue by banesullivan** [girder/large_image#739]
Would it make sense to support URLs in the GDAL source? so that `GDALFileTileSource('s3://....')` works out of the box? This logic could be implemented with:

```py
import pathlib
from urllib.parse import urlparse


def make_vsi(url: str, **options):
    if str(url).startswith("s3://"):
        s3_path = url.replace("s3://", "")
        vsi = f"/vsis3/{s3_path}"
    else:
        gdal_options = {
            "url": str(url),
            "use_head": "no",
            "list_dir": "no",
        }
        gdal_options.update(options)
        vsi = f"/vsicurl?{urlencode(gdal_options)}"
    return vsi


def get_clean_filename(filename: str):
    if str(filename).startswith("/vsi"):
        return filename
    parsed = urlparse(str(filename))
    if parsed.scheme in ["http", "https", "s3"]:
        return make_vsi(filename)
    # Otherwise, treat as local path on Disk
    filename = pathlib.Path(filename).expanduser().absolute()
    if not filename.exists():
        raise OSError(f"Path does not exist: {filename}")
    return filename

``` 

From https://github.com/banesullivan/localtileserver/blob/3b368ffed5491ec7daa84551cc24ff5995039a22/localtileserver/tileserver/utilities.py#L139-L164

**Comment by manthey** [comment]
I thought you already could just specify `/vsis3/...` or `/vsicurl/...`.  Is this just converting a scheme specification for more convenience?

**Comment by banesullivan** [comment]
Yes, this is purely for user convienance

**Comment by manthey** [comment]
If you make a PR to this end, you should be able to exclude the code with `expanduser`.  You should also include `ftp` as an allowed schema, since gdal supports that with vsicurl.  Also, `urlparse` is cheap enough, that I would probably simplify your second function to:
```
if urlparse(str(filename)).scheme in {"http", "https", "ftp", "s3"}:
    filename = make_vsi(filename)
```
