### ISSUE TITLE
Source GDAL large-image depend should be updated or freed

### ISSUE THREAD

**Issue by banesullivan** [girder/large_image#743]
https://github.com/girder/large_image/blob/d68f3949000a5d2df63a60c8f8b2a6a06ff51a5d/sources/gdal/setup.py#L46

This should either be updated to `>=1.9` or freed altogether. 

Because of 

https://github.com/girder/large_image/blob/d68f3949000a5d2df63a60c8f8b2a6a06ff51a5d/sources/gdal/large_image_source_gdal/__init__.py#L40

I have to set `>=1.9` in the conda-forge recipe in https://github.com/conda-forge/large-image-source-gdal-feedstock/pull/5

**Comment by manthey** [comment]
Probably removing that `>=1.0.0` is the right thing to do.  I don't want to chase version specifications in the submodules.

**Comment by banesullivan** [comment]
I agree - though I think I have to set this version for conda

**Comment by manthey** [comment]
> I agree - though I think I have to set this version for conda

After large-image updates, wouldn't rerunning conda CI for the large-image-source-gdal package be sufficient?

**Comment by banesullivan** [comment]
In theory after waiting long enough (~4 hours), probably. However, I am more concerned about mismatched versions with users on conda. The setup.py here does not restrict the versions to make dev installs easier. If there were an easy way to set the version constraint when building the wheels I think we should do it and be explicit about dependencies.

**Comment by manthey** [comment]
In the `make_wheels.sh` and `release_pypi.sh` scripts, we could do something like: `find . -name setup.py -exec sed -i "s/ 'large-image'/ 'large-image==$VERSION'/g" {} +;` and `find . -name setup.py -exec sed -i "s/ 'girder-large-image'/ 'girder-large-image==$VERSION'/g" {} +;` before the build.

**Comment by manthey** [comment]
I don't know if that would percolate appropriately to conda.

**Comment by banesullivan** [comment]
> I don't know if that would percolate appropriately to conda.

It wouldn't... I don't think there's a clean way of automatically bumping the depend in the conda recipe
