### ISSUE TITLE
Categorical color palettes

### ISSUE THREAD

**Issue by banesullivan** [girder/large_image#753]
If passing two HEX colors as the palette, the returned thumbnail or tiles interpolate the values between those two colors. 

Is there a way to use the color maps as categorical colors? e.g., split the min/max range into the number of colors in the palette and assign those values directly to the given colors.

**Comment by banesullivan** [comment]
For example, if I use the palette `["#000", "#f00"]`, this right now interpolates the values between those colors. This is great most of the time, but what if I want the colors to be either `"#000"` or `"#f00"` and nothing else?

Current resulting thumbnail:

![thumbnail](https://user-images.githubusercontent.com/22067021/148654820-e71e5711-1ff9-436a-9f07-55ff063d9028.png)


Example tile result:

![download](https://user-images.githubusercontent.com/22067021/148654918-c2b789c3-48f7-45c6-a979-4ae846fe58ac.png)

But I actually want something like:

<img width="624" alt="Screen Shot 2022-01-08 at 11 17 40 AM" src="https://user-images.githubusercontent.com/22067021/148655193-4b8990c9-dd29-4d8a-8925-8e15d2ab6e0c.png">

**Comment by manthey** [comment]
The naming `"scheme": "discrete"` is inherited from the mapnik source.  We could make aliases so `categorical` could b used instead of `discrete`.
