### ISSUE TITLE
Tile out of bounds error type

### ISSUE THREAD

**Issue by banesullivan** [girder/large_image#808]
I stumbled on this error handling this morning and thought we should have a specific error type in large-image for handling bad tile requests.

https://github.com/atlascope/atlascope/blob/da9b5ac19d69101d11990c6a6eea5a1f349a885f/atlascope/core/rest/endpoints/tile_endpoints.py#L137-L146

My rationale: if the z/x/y is out of bounds, then this should not throw a server error but return some sore of http error response. By having a custom error class for this issue in large-image, we could more easily capture this and handle it in rest interfaces

The exception class for this should subclass `TileSourceError` for consistency and backward compatibility

**Comment by manthey** [comment]
I think there are only two places in the code that throws this error: https://github.com/girder/large_image/blob/master/large_image/tilesource/base.py#L1439 and https://github.com/girder/large_image/blob/master/sources/pil/large_image_source_pil/__init__.py#L176
That second one could just call `self._xyzInRange` like all of the other tile sources, and then there would be only one point.

Feel free to add a new error class and modify `_xyzInRange` to throw it.

**Comment by banesullivan** [comment]
Thanks for pointing me to the right places. I'll see if I can whip something together
