### ISSUE TITLE
Allow returning bounding box information with annotations

### ISSUE THREAD

**Issue by manthey** [girder/large_image#850]
We track bounding boxes with annotations.  Some consumers of annotations would find these useful.

**Comment by cooperlab** [comment]
+1 for this.

**Comment by manthey** [comment]
Internally, we store something like `"bbox" : { "lowz" : 0, "highz" : 0, "lowx" : 4532.93, "lowy" : 257.67, "highx" : 4545.93, "highy" : 268.67, "details" : 4, "size" : 17.029386365926403 }` for every annotation element in the database.

There are two approaches I see:

(1) This could be appended to the returned element (e.g., `{"type": "polyline", "id": ..., ..., "_bbox": {...}}"`, but this would technically violate the schema.  This could be implemented by adding a parameter to the `GET annotation/{id}` endpoint.  I think that when ingesting annotations, we could just discard any keys that begin with `_` to avoid causing problems if the results were returned directly.

(2) Alternately, we could have a separate method that would return the bounding box information with the ids and therefore not be related to the schema.   This would add a new endpoint (`GET annotation/{id}/boundingboxes`?).

Either way, from python, it probably would be exposed as a flag on the `yieldElements` method in the annotationelement model and in the `load` method in the annotation model.

**Comment by brendonlutnick** [comment]
Either approach would work. 

Not sure about the specifics of the schema, but my hacky way of doing this for now is to write these into the description field using json.dump. 

Could these be simply added somewhere as a block of formatted json data?

**Comment by manthey** [comment]
There are bounding boxes in the database at the element level.  We could also store or compute a bounding box at the annotation level (but we don't currently -- this is the combined extents of the element bounding boxes for the entire annotation).  The virtue of the fields in the database (versus storing them as a block elsewhere) is that they are maintained to be correct, whereas if they were external to that we would need a step to ensure synchronization.

**Comment by brendonlutnick** [comment]
Got it! I'll defer to you on what's the best way to proceed, I can modify my code to work with either method easily
