### ISSUE TITLE
create a rasterio driver for large-image?

### ISSUE THREAD

**Issue by 12rambau** [girder/large_image#898]
don't get me wrong the question is not "is geospatial version of large_image necessary" but more about the use of GDAL itself. 

GDAL is a great library but it has the really bad habit of being the worst possible neighbor in a python environment. I started to use https://localtileserver.banesullivan.com/installation/index.html for my project and since I publish the latest version all the pip-related environments failed because of gdal inconsistency and version crash. 

I search in the GDAL repository itself and there is a very long thread of about a potential wheel distribution for GDAL https://github.com/OSGeo/gdal/issues/3060 that seems on stale. 

As large_image seems to be developed for python environments being pip-friendly seems like a desirable objective. Do you already considered using a pure rasterio driver ?

**Comment by manthey** [comment]
It isn't hard to add additional tile sources -- there are a few basic functions (getTile, getMetadata) that need to be defined.  The __init__ method needs to determine the image size and a few other parameters.

The main developers mostly work in environments where GDAL is available (via our self-published linux wheels or via conda), so this hasn't been needed -- but we always encourage additional tile sources and could be convinced this could be added as part of our efforts.

**Comment by manthey** [comment]
Added in #1115
