### ISSUE TITLE
why is get_bounds storing all the tile corners in a dict ? 

### ISSUE THREAD

**Issue by 12rambau** [girder/large_image#917]
https://github.com/girder/large_image/blob/7b5142b7576d7dbd2c392ce16016c5876b0e2e9c/sources/gdal/large_image_source_gdal/__init__.py#L480

why is get_bounds storing all the tile corners in a dict instead of only the 4 coordinates (xmin, ymin, xmax, ymax) ? 
I have the feeling that it's never really used afterward and it makes the dict overly complicated.

**Comment by manthey** [comment]
The short answer is rotated and non-affine coordinate systems.  Think of a stereographic projection.

**Comment by 12rambau** [comment]
😮 I wanted to forget about  stereographic  projection after my crystallography class. I'm glad that rasterio is not supporting it (https://rasterio.readthedocs.io/en/latest/api/rasterio.transform.html) that's one problem out my list for the rasterio source

**Comment by 12rambau** [comment]
sorry to reopen but that's in the same place. I try to reimplement the bounds with the 4 corners as I need to take into consideration the exotic projections and I don't manage to understand the whole verification process. 

here you do some testing on the corners values. in order to make sure they fit in -90, 90, -180, 180.
https://github.com/girder/large_image/blob/2ca878e1318eaa43c754a27587530746625a9b83/sources/gdal/large_image_source_gdal/__init__.py#L516

My question is simple why do we consider that the tested projection is epsg:4326 ? I see that is work as these corner values are only called here

**Comment by 12rambau** [comment]
sorry for the noise I understood, you are using the transform to get this values unprojected (i.e. 4326) and they are then reprojected in srs using the transformer
