### ISSUE TITLE
why not using a with statement ? 

### ISSUE THREAD

**Issue by 12rambau** [girder/large_image#922]
In this section of the gdal tilesource, there is a complex structure to set and unlink tmp files using os. could it be possible to use a with statement instead (https://stackoverflow.com/a/39984066/6734243) ? letting the lib responsible for cleaning.

https://github.com/girder/large_image/blob/d60004b4810efa14c396281bdaf858d97dd87997/sources/gdal/large_image_source_gdal/__init__.py#L1131

**Comment by 12rambau** [comment]
along with this question, why do you use a prefix in your file ? I see the point of using a suffix to make sure the file is a tiff but the name you set is never used right ?

**Comment by manthey** [comment]
I think it was laziness on my part -- in the base tile source, the `tiledRegion_` file IS the output.  In the gdal source, it is just a temp file, so it doesn't need the prefix and could use a context manager.  Using `with tempfile.NamedTemporaryFile(suffix='.tiff') as tf:` would be more appropriate here (and then `tf.file.close()`, `tempPath = tf.name`).

**Comment by 12rambau** [comment]
why do you want to close the handle manually ? I think it's closed when you exit the context manager ?

**Comment by manthey** [comment]
We really just want a unique temporary name that is guaranteed to be free and can be created, but we are using vips to write the first image and gdal to warp it to the second.  If we don't close the handle, then there is a file of the specified name open where the libraries want to create a new file, which, at the very least is confusing.
