### ISSUE TITLE
TIFF files - missing magnification

### ISSUE THREAD

**Issue by janglinko-dac** [girder/large_image#968]
Hello, 
when I'm reading tiff files and the magnification is None in the metadata, some functions converting scales and `getSingleTile` seems to not work appropriate. 
I would like to inject the dummy magnification value to the metadata, but I couldn't find a way how to do it.

**Comment by manthey** [comment]
The magnification is read differently depending on the tile source.  It is abstracted to a class method `getNativeMagnification` which returns a dict containing the magnification and base pixel resolution in millimeters.

You could override this, like so:
```
ts = large_image.open(<path to the file>)
ts.getNativeMagnification = lambda: dict(magnification=40, mm_x=0.00025, mm_y=0.00025)
```
, obviously putting in whatever magnification and resolution is appropriate.

**Comment by janglinko-dac** [comment]
Tanks a lot!
